Data/Code/Product_Entry_Demo/Product_Entry_Demo/Models/Product_Entry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Product_Entry_Demo.Models
{
    public class Product_Entry
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public bool IsIGSTApplicable { get; set; }
        public string Purchase_Date { get; set; }
        public string Expiry_Date { get; set; }
        public string Color { get; set; }
    }
}

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Product_Entry_Demo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Controllers/Product_EntryController.cs
using Product_Entry_Demo.Library.BAL;
using Product_Entry_Demo.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Product_Entry_Demo.Controllers
{
    public class Product_EntryController : Controller
    {
        // GET: Product_Entry
        public ActionResult Add_Product_Entry()
        {
            ViewBag.ColorList = ListData(typeof(Product_Entry_Demo.Library.Constants.ColorList));
            return View();
        }
       
        [HttpPost]
        public ActionResult Add_Product_Entry(Product_Entry product)
        {
            BalProduct_Entry balProduct_Entry = new BalProduct_Entry();
            Product_Entry productEntry = new Product_Entry();
                try
                {
                    bool IsSave = false;
                balProduct_Entry.ID = product.ID;
                balProduct_Entry.Name = product.Name;
                balProduct_Entry.Price = product.Price;
                balProduct_Entry.Quantity = product.Quantity;
                balProduct_Entry.IsIGSTApplicable = product.IsIGSTApplicable;
                balProduct_Entry.Purchase_Date = product.Purchase_Date;
                balProduct_Entry.Expiry_Date = product.Expiry_Date;
                balProduct_Entry.Color = product.Color;


                balProduct_Entry.baproduct_lst = balProduct_Entry.Select_ProductEntry_ById(0).Where(m=>m.Name==product.Name).ToList();
                    if (balProduct_Entry.baproduct_lst.Count() == 0)
                    {
                        
                            if (product.ID == 0)
                            {

                                IsSave = balProduct_Entry.InsertProduct_Entry(balProduct_Entry);
                                TempData["UsersaveUpdate"] = "Product Entry Saved Successfully.";

                            }
                        
                    }
                    else
                    {                        
                        TempData["UserSaveUpdate"] = "Name Allredy Exist.";
                    }
                    
                }
                catch (Exception ex)
                {
                }
                 return RedirectToAction("GetAllProduct_Entry");
            
        }

        public ActionResult GetAllProduct_Entry()
        {
                BalProduct_Entry balProduct = new BalProduct_Entry();               
                    ViewBag.ProductDetails= balProduct.Select_ProductEntry_ById(0).ToList();
                    ViewBag.UserTitle = "Other User";
                return View();
            
        }
        public ActionResult AllProduct_Entry()
        {
            BalProduct_Entry balProduct = new BalProduct_Entry();

            balProduct.baproduct_lst = balProduct.Select_ProductEntry_ById(0).ToList();
            var Selectdatalst = from s in balProduct.baproduct_lst select new { s.ID, s.Name, s.Price, s.Quantity, s.IsIGSTApplicable, s.Purchase_Date, s.Expiry_Date,s.Color };
            return Json(new { data = Selectdatalst }, JsonRequestBehavior.AllowGet);
        }

        public List<string> ListData(Type type)
        {
            Type InLinenumType = type;
            var _InlinenumValues = InLinenumType.GetEnumValues();
            List<string> _LstValue = new List<string>();
            foreach (var value in _InlinenumValues)
            {
                MemberInfo memberInfo = InLinenumType.GetMember(value.ToString()).First();
                var descriptionAttribute = memberInfo.GetCustomAttribute<DescriptionAttribute>();
                string val = descriptionAttribute.Description.ToString();
                _LstValue.Add(val);
            }
            return _LstValue;
        }
        
    }
}

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Views/Product_Entry/Add_Product_Entry.cshtml
@model Product_Entry_Demo.Models.Product_Entry
@{
    ViewBag.Title = "Add_Product_Entry";

    List<SelectListItem> lstColorLst = new List<SelectListItem>();

    foreach (var item in ViewBag.ColorList)
    {
        lstColorLst.Add(new SelectListItem() { Text = item });
    }

}

@*<script src="~/scripts/SweetAlert/jquery-1.10.2.js"></script>
    <link href="~/scripts/SweetAlert/sweetalert.css" rel="stylesheet" />
    <script src="~/scripts/SweetAlert/sweetalert.js"></script>
    <script>

        @if (TempData["UsersaveUpdate"] != null)
        {
             <text>
    $(window).load(function () {
        $(document).ready(function () {
            sweetAlert({ title: "Message", text: "@TempData["UsersaveUpdate"]", type: "success" });
        });
    });
    </text>


        }

    </script>
    <script type="text/javascript">
        @if (TempData["UserEmailExist"] != null)
        {
           <text>
    $(window).load(function () {
        $(document).ready(function () {
            sweetAlert({ title: "Message", text: "@TempData["UserEmailExist"]", type: "error" });
        });
    });
    </text>

        }
    </script>
    <script type="text/javascript">
        @if (TempData["UserExist"] != null)
        {
           <text>
    $(window).load(function () {
        $(document).ready(function () {
            sweetAlert({ title: "Message", text: "@TempData["UserExist"]", type: "error" });
        });
    });
    </text>

        }
    </script>*@
<div class="row">
    <div class="col-sm-9">

        @using (Html.BeginForm("Add_Product_Entry", "Product_Entry", FormMethod.Post, new
        {
            enctype = "multipart/form-data",
            @id = "formproductEntry"

        }))
        {
            <div class="panel panel-body" style="width:130%;">
                <div class="panel-body" style="width:100%;">
                    <div class="box box-primary">
                        <div class="col-sm-12" style="background-color:white">
                            <div class="form-group">
                                <div class="col-sm-1"></div>
                                <div class="col-sm-5">
                                    @Html.HiddenFor(m => m.ID, new { @id = "user_id", @class = "form-control" })
                                    <label class="control-label">Name <span class="asterisk">*</span> </label>
                                    @Html.TextBoxFor(m => m.Name, new { placeholder = "Name", @class = "form-control LoginText" })
                                    <p id="p1" style="color: #B94A48"></p>
                                </div>
                                <div class="col-sm-5">
                                    <label class="control-label">Price <span class="asterisk">*</span> </label>
                                    @Html.TextBoxFor(m => m.Price, new {@type= "number", placeholder = "Price", @class = "form-control LoginText" })
                                    <p id="p2" style="color: #B94A48"></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12" style="background-color:white">
                            <div class="form-group">
                                <div class="col-sm-1"></div>
                                <div class="col-sm-5">
                                    <label class="control-label">Quantity<span class="asterisk">*</span> </label>
                                    @Html.TextBoxFor(m => m.Quantity, new { @type = "number", placeholder = "Quantity", @class = "form-control LoginText" })
                                    <p id="p3" style="color: #B94A48"></p>
                                </div>
                                <div class="col-sm-5">
                                    <label class="control-label">State<span class="asterisk">*</span> </label>
                                    @Html.DropDownListFor(m => m.Color, lstColorLst, "Select Color", new { @id = "Color", @name = "Color", @class = "form-control LoginText" })
                                    <p id="p4" style="color: #B94A48"></p>
                                </div>
                            </div>
                        </div><!-- col-sm-6 -->
                        <div class="col-sm-12" style="background-color:white">
                            <div class="form-group">
                                <div class="col-sm-1"></div>
                                <div class="col-sm-5">
                                    <label class="control-label">Purchase Date<span class="asterisk">*</span> </label>
                                    @*<div class="input-group date">*@
                                        @Html.TextBoxFor(m => m.Purchase_Date, new { @autocomplete = "off", @placeholder = "dd/mm/yyyy", @name = "Purchase_Date", @id = "Purchase_Date" , @class = "form-control LoginText" })

                                    @*</div>*@
                                </div>

                                <div class="col-sm-5">
                                    <label class="control-label">Expiry Date<span class="asterisk" id="Expiry_Dates">*</span> </label>
                                    @*<div class="input-group date">*@
                                        @Html.TextBoxFor(m => m.Expiry_Date, new { @autocomplete = "off", @placeholder = "dd/mm/yyyy", @name = "Expiry_Date", @id = "Expiry_Date", @class = "form-control LoginText" })

                                    @*</div>*@
                                </div>

                            </div>
                        </div><!-- col-sm-6 -->

                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-12">
                                    <a class="btn btn-info" id="btn_back" href="/Product_Entry/GetAllProduct_Entry" name="btn_back">Back</a>
                                    <input type="submit" value="@ViewBag.ButtonName" name="BtnSave" class="btn btn-rounded btn-success mb-3" style="float: right;">
                                    <button type="reset" class="btn btn-white"><i class="fa fa-rotate-right"></i> Reset</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section scripts{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <script>

        $("#Purchase_Date").datepicker(
            {
                format: "dd/mm/yyyy",
                todayHighlight: true,
                autoclose: true,
            });
        $("#Expiry_Date").datepicker(
            {
                format: "dd/mm/yyyy",
                todayHighlight: true,
                autoclose: true,
                startDate: new Date()
            });
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/additional-methods.min.js"></script>
    <script type="text/javascript">


        $(document).ready(function () {

            $("#formproductEntry").validate({
                // Specify validation rules
                rules: {
                    Name: {

                        required: true,

                    },
                    Price: {

                        required: true,

                    },
                    Quantity: {
                        required: true,

                    },
                    IsIGSTApplicable: {

                        required: true,

                    },

                    Purchase_Date: {

                        required: true,

                    },
                    Expiry_Date: {

                        required: true,

                    },
                    Color: {

                        required: true
                    },

                },
                // Specify validation error messages
                messages: {
                    Name: {

                        required: "<span class='text-danger'>Name Required.</span>",

                    },
                    Price: {

                        required: "<span class='text-danger'>Price Required.</span>",

                    },
                    Quantity: {

                        required: "<span class='text-danger'>Quantity Required.</span>"
                    },
                    IsIGSTApplicable: {

                        required: "<span class='text-danger'>Is IGST Applicable Required.</span>",

                    },
                    Purchase_Date: {

                        required: "<span class='text-danger'>Purchase Date Required.</span>",

                    },
                    Expiry_Date: {

                        required: "<span class='text-danger'>Expiry Date Required.</span>",

                    },
                    Color: {

                        required: "<span class='text-danger'>Color Required.</span>",

                    },
                },
                // Make sure the form is submitted to the destination defined
                // in the "action" attribute of the form when valid
                submitHandler: function (form) {
                    form.submit();
                }
            });

            //$('.text-danger').addClass("text-danger");

        });

    </script>
}

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Views/Product_Entry/GetAllProduct_Entry.cshtml
@{
    /**/

    ViewBag.Title = "GetAllProduct_Entry";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-success" href="/Product_Entry/Add_Product_Entry">
            <i class="fa fa-plus-square"></i>
            Add New
        </a>
    </div>
</div>
<br />
<div class="row">
    <div class="form-horizontal">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <table id="ProductEntryTbl" class="table table-bordered table-hover" style="width:100%;white-space: nowrap;">
                                <thead>
                                    <tr>
                                        <th>Sr.No.</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Is GST Applicable</th>
                                        <th>Purchase Date</th>
                                        <th>Expiry Date</th>
                                        <th>Color</th>
                                    </tr>
                                </thead>
                                @*@if (ViewBag.ProductDetails != null)
                                    {
                                        foreach (var items in ViewBag.ProductDetails)
                                        {
                                            <tbody>
                                                <tr>
                                                    <td>@items.ID</td>
                                                    <td>@items.Name</td>
                                                    <td>@items.Price</td>
                                                    <td>@items.Quantity</td>
                                                    <td>@items.IsIGSTApplicable</td>
                                                    <td>@items.Purchase_Date</td>
                                                    <td>@items.Expiry_Date</td>
                                                    <td>@items.Color</td>
                                                </tr>
                                            </tbody>
                                        }
                                    }*@
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
@section scripts{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/select/1.2.7/css/select.dataTables.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.4/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.4/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.4/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.4/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.2.7/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

    <script src="//bartaz.github.io/sandbox.js/jquery.highlight.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.9/features/searchHighlight/dataTables.searchHighlight.min.js"></script>
    @*<link href="//cdn.datatables.net/plug-ins/1.10.9/features/searchHighlight/dataTables.searchHighlight.css" rel="stylesheet" type="text/css" />*@

    <script>
        $(document).ready(function () {

            var t = $("#ProductEntryTbl").DataTable({

                "ajax": {
                    "url": '/Product_Entry/AllProduct_Entry',
                    "type": "GET",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "ID", "autoWidth": true },
                    { "data": "Name", "autoWidth": true },
                    { "data": "Price", "autoWidth": true },
                    { "data": "Quantity", "autoWidth": true },
                    { "data": "IsIGSTApplicable", "autoWidth": true },
                    { "data": "Purchase_Date", "autoWidth": true },
                    { "data": "Expiry_Date", "autoWidth": true },
                    { "data": "Color", "autoWidth": true },

                ],
                "dom": "Bflrtip",
                "buttons": [
                    {

                        extend: 'copy', className: 'btn bg-blue'

                    },
                    {
                        extend: 'excel', className: 'btn bg-orange'


                    },
                    {
                        extend: 'csv', className: 'btn btn-info'


                    },
                    {
                        extend: 'pdf', className: 'btn btn-success',
                        extend: 'pdfHtml5'

                    },

                    {
                        extend: 'print', className: 'btn bg-red'
                    }

                ],
                alphabetSearch: {
                    column: 1
                },
                responsive: true,
                "order": [[0, 'desc']],
                "scrollX": true,
                searchHighlight: true
            });
            t.on('order.dt search.dt', function () {
                t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1;
                });
            }).draw();
        });</script>
}

Data/Code/Product_Entry_Demo/Product_Entry_Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>